# Generated by Django 6.0 on 2025-12-08 03:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='新对话', max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('message_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('system', '系统')], max_length=10)),
                ('content', models.TextField()),
                ('context_type', models.CharField(choices=[('selection', '选中文本'), ('formula', '公式'), ('chunk', '内容块'), ('document', '文档'), ('none', '无')], default='none', max_length=20)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.conversation')),
            ],
            options={
                'db_table': 'agent_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('planning', '规划中'), ('executing', '执行中'), ('waiting', '等待用户'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('plan', models.JSONField(blank=True, default=list)),
                ('execution_history', models.JSONField(blank=True, default=list)),
                ('result', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('iterations', models.IntegerField(default=0)),
                ('execution_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agent.conversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agent.message')),
            ],
            options={
                'db_table': 'agent_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_input', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('timeout', '超时')], default='pending', max_length=20)),
                ('output', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('execution_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='agent.agenttask')),
            ],
            options={
                'db_table': 'agent_tool_calls',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(choices=[('preference', '用户偏好'), ('knowledge', '知识'), ('conversation', '对话摘要'), ('feedback', '反馈'), ('habit', '习惯')], max_length=20)),
                ('content', models.TextField()),
                ('related_concept', models.CharField(blank=True, default='', max_length=200)),
                ('importance', models.FloatField(default=0.5)),
                ('access_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_memories',
                'ordering': ['-importance', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'memory_type'], name='agent_memor_user_id_890de5_idx'), models.Index(fields=['user', '-importance'], name='agent_memor_user_id_5bebc9_idx'), models.Index(fields=['related_concept'], name='agent_memor_related_aaf09c_idx'), models.Index(fields=['expires_at'], name='agent_memor_expires_a948eb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='agent_conve_user_id_230a21_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['document'], name='agent_conve_documen_6d7cff_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='agent_messa_convers_7ad657_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['role'], name='agent_messa_role_a93a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttask',
            index=models.Index(fields=['conversation', '-created_at'], name='agent_tasks_convers_5e8179_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttask',
            index=models.Index(fields=['status'], name='agent_tasks_status_77f28c_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttask',
            index=models.Index(fields=['created_at'], name='agent_tasks_created_13f28d_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcall',
            index=models.Index(fields=['task', 'created_at'], name='agent_tool__task_id_3a2c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcall',
            index=models.Index(fields=['tool_name'], name='agent_tool__tool_na_1b478b_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcall',
            index=models.Index(fields=['status'], name='agent_tool__status_8a23b6_idx'),
        ),
    ]
