# Generated by Django 6.0 on 2025-12-08 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('documents', '0002_remove_document_documents_d_user_id_ffacf2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='agent_conve_documen_6d7cff_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='agent_messa_role_a93a2b_idx',
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'is_active'], name='agent_conve_user_id_3d10ee_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['document', '-updated_at'], name='agent_conve_documen_85205b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'role'], name='agent_messa_convers_5b0853_idx'),
        ),
    ]
