# Generated by Django 6.0 on 2025-12-09 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0006_formula_label_formula_order'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('follow', '关注'), ('unfollow', '取消关注'), ('like', '点赞'), ('unlike', '取消点赞'), ('comment', '评论'), ('collect', '收藏'), ('upload_document', '上传文档'), ('publish_document', '发布文档')], help_text='活动类型', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='相关对象ID', null=True)),
                ('description', models.TextField(blank=True, help_text='活动描述')),
                ('is_private', models.BooleanField(default=False, help_text='是否为私密活动')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动流',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='被评论的对象ID')),
                ('content', models.TextField(help_text='评论内容', max_length=1000)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除')),
                ('likes_count', models.PositiveIntegerField(default=0, help_text='点赞数')),
                ('replies_count', models.PositiveIntegerField(default=0, help_text='回复数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(default='默认收藏夹', help_text='收藏夹名称', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='收藏备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '文档收藏',
                'verbose_name_plural': '文档收藏',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '关注关系',
                'verbose_name_plural': '关注关系',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='被点赞的对象ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='个人简介', max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='followers_count',
            field=models.PositiveIntegerField(default=0, help_text='粉丝数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='following_count',
            field=models.PositiveIntegerField(default=0, help_text='关注数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_username',
            field=models.CharField(blank=True, help_text='GitHub用户名', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='是否推荐用户'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='是否验证用户'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, help_text='获得点赞数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, help_text='所在地', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='public_documents_count',
            field=models.PositiveIntegerField(default=0, help_text='公开文档数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, help_text='个人网站'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='users_custo_usernam_a8ad03_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['followers_count'], name='users_custo_followe_07a2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['following_count'], name='users_custo_followi_960f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_verified'], name='users_custo_is_veri_8bba47_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_featured'], name='users_custo_is_feat_97e06a_idx'),
        ),
        migrations.AddField(
            model_name='activity',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='相关内容类型', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='activity',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='目标用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(help_text='被评论的内容类型', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父评论', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentcollection',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentcollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(help_text='关注者', on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(help_text='被关注者', on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(help_text='被点赞的内容类型', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', '-created_at'], name='users_activ_user_id_5d6877_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['target_user', '-created_at'], name='users_activ_target__132e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['action', '-created_at'], name='users_activ_action_6cbb5b_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['-created_at'], name='users_activ_created_810836_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id', '-created_at'], name='users_comme_content_5458c9_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='users_comme_user_id_853883_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', '-created_at'], name='users_comme_parent__d8fcca_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created_at'], name='users_comme_created_e9f55a_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-likes_count'], name='users_comme_likes_c_d094b8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollection',
            index=models.Index(fields=['user', '-created_at'], name='users_docum_user_id_5099cf_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollection',
            index=models.Index(fields=['document', '-created_at'], name='users_docum_documen_c408c6_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollection',
            index=models.Index(fields=['collection_name'], name='users_docum_collect_5a3c65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentcollection',
            unique_together={('user', 'document')},
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', '-created_at'], name='users_follo_followe_b6ba3d_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following', '-created_at'], name='users_follo_followi_f424c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['content_type', 'object_id'], name='users_like_content_2fb2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', '-created_at'], name='users_like_user_id_bf796a_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['-created_at'], name='users_like_created_918ddb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
