# Generated by Django 6.0 on 2025-12-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_activity_comment_documentcollection_follow_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='object_id',
            field=models.CharField(blank=True, help_text='相关对象ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.CharField(help_text='被评论的对象ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.CharField(help_text='被点赞的对象ID', max_length=255),
        ),
    ]
