# Generated by Django 6.0 on 2025-12-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_activity_object_id_alter_comment_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(blank=True, help_text='认证提供商 (google, local)', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google OAuth ID', max_length=100, null=True, unique=True),
        ),
    ]
