# Generated by Django 6.0 on 2025-12-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_auth_provider_customuser_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wechat_openid',
            field=models.CharField(blank=True, help_text='微信 OpenID', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wechat_unionid',
            field=models.CharField(blank=True, help_text='微信 UnionID', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(blank=True, help_text='认证提供商 (google, wechat, local)', max_length=20),
        ),
    ]
