# Generated by Django 5.2.9 on 2025-12-13 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_wechat_openid_customuser_wechat_unionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('follow', '关注'), ('unfollow', '取消关注'), ('friend_request', '发送好友请求'), ('friend_accept', '接受好友请求'), ('friend_reject', '拒绝好友请求'), ('friend_remove', '删除好友'), ('like', '点赞'), ('unlike', '取消点赞'), ('comment', '评论'), ('collect', '收藏'), ('upload_document', '上传文档'), ('publish_document', '发布文档'), ('send_message', '发送消息')], help_text='活动类型', max_length=20),
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('private', '私人聊天'), ('group', '群组聊天')], default='private', help_text='聊天类型', max_length=10)),
                ('name', models.CharField(blank=True, help_text='聊天名称（群聊时使用）', max_length=100)),
                ('description', models.TextField(blank=True, help_text='聊天描述')),
                ('avatar', models.ImageField(blank=True, help_text='聊天头像', null=True, upload_to='chat_avatars/')),
                ('message_count', models.PositiveIntegerField(default=0, help_text='消息数量')),
                ('is_active', models.BooleanField(default=True, help_text='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='创建者', on_delete=django.db.models.deletion.CASCADE, related_name='created_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '聊天会话',
                'verbose_name_plural': '聊天会话',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件'), ('voice', '语音'), ('video', '视频'), ('system', '系统消息')], default='text', help_text='消息类型', max_length=10)),
                ('content', models.TextField(help_text='消息内容')),
                ('file_url', models.URLField(blank=True, help_text='文件URL')),
                ('file_name', models.CharField(blank=True, help_text='文件名', max_length=255)),
                ('file_size', models.BigIntegerField(default=0, help_text='文件大小（字节）')),
                ('is_edited', models.BooleanField(default=False, help_text='是否已编辑')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除')),
                ('is_read', models.BooleanField(default=False, help_text='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(help_text='所属聊天', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.chatconversation')),
                ('reply_to', models.ForeignKey(blank=True, help_text='回复的消息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='users.chatmessage')),
                ('sender', models.ForeignKey(help_text='发送者', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='last_message',
            field=models.ForeignKey(blank=True, help_text='最后一条消息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.chatmessage'),
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', '成员'), ('admin', '管理员'), ('owner', '群主')], default='member', help_text='角色', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(auto_now=True, help_text='最后阅读时间')),
                ('is_active', models.BooleanField(default=True, help_text='是否活跃')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.chatconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '聊天参与者',
                'verbose_name_plural': '聊天参与者',
            },
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='participants',
            field=models.ManyToManyField(help_text='聊天参与者', related_name='chat_conversations', through='users.ChatParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('accepted', '已确认'), ('blocked', '已屏蔽')], default='pending', help_text='好友关系状态', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(help_text='接收好友请求的用户', on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='发送好友请求的用户', on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '好友关系',
                'verbose_name_plural': '好友关系',
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', '-created_at'], name='users_chatm_convers_4a482d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', '-created_at'], name='users_chatm_sender__d8cbe9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_read'], name='users_chatm_is_read_23143f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['conversation', 'user'], name='users_chatp_convers_58fb58_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user', '-joined_at'], name='users_chatp_user_id_db3bf3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('conversation', 'user')},
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['-updated_at'], name='users_chatc_updated_82a049_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['type'], name='users_chatc_type_c6a02b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['is_active'], name='users_chatc_is_acti_92ed9b_idx'),
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['sender', '-created_at'], name='users_frien_sender__6b55f4_idx'),
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['receiver', '-created_at'], name='users_frien_receive_45bf3a_idx'),
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['status'], name='users_frien_status_6b7f17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('sender', 'receiver')},
        ),
    ]
