# Generated by Django 5.2.9 on 2025-12-13 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_activity_action_chatconversation_chatmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('follow', '关注'), ('unfollow', '取消关注'), ('friend_request', '发送好友请求'), ('friend_accept', '接受好友请求'), ('friend_reject', '拒绝好友请求'), ('friend_remove', '删除好友'), ('like', '点赞'), ('unlike', '取消点赞'), ('comment', '评论'), ('collect', '收藏'), ('upload_document', '上传文档'), ('publish_document', '发布文档'), ('send_message', '发送消息'), ('create_group', '创建学习小组'), ('join_group', '加入学习小组'), ('leave_group', '离开学习小组'), ('invite_to_group', '邀请加入小组')], help_text='活动类型', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='name',
            field=models.CharField(blank=True, help_text='聊天名称', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='聊天参与者', related_name='chat_conversations', through='users.ChatParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='type',
            field=models.CharField(choices=[('private', '私人聊天'), ('group', '群组聊天'), ('channel', '频道聊天')], default='private', help_text='聊天类型', max_length=10),
        ),
        migrations.CreateModel(
            name='GroupChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='频道名称', max_length=100)),
                ('description', models.TextField(blank=True, help_text='频道描述')),
                ('channel_type', models.CharField(choices=[('text', '文本频道'), ('voice', '语音频道')], default='text', help_text='频道类型', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='排序位置')),
                ('is_private', models.BooleanField(default=False, help_text='是否为私有频道')),
                ('message_count', models.PositiveIntegerField(default=0, help_text='消息数量')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='最后消息时间', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='创建者', on_delete=django.db.models.deletion.CASCADE, related_name='created_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '小组频道',
                'verbose_name_plural': '小组频道',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='group_channel',
            field=models.OneToOneField(blank=True, help_text='关联的频道', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='users.groupchannel'),
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='小组名称', max_length=100)),
                ('description', models.TextField(blank=True, help_text='小组描述')),
                ('avatar', models.ImageField(blank=True, help_text='小组头像', null=True, upload_to='group_avatars/')),
                ('cover_image', models.ImageField(blank=True, help_text='封面图片', null=True, upload_to='group_covers/')),
                ('privacy', models.CharField(choices=[('public', '公开'), ('private', '私有')], default='private', help_text='小组隐私设置', max_length=10)),
                ('member_count', models.PositiveIntegerField(default=1, help_text='成员数量')),
                ('channel_count', models.PositiveIntegerField(default=0, help_text='频道数量')),
                ('allow_invites', models.BooleanField(default=True, help_text='允许成员邀请他人')),
                ('require_approval', models.BooleanField(default=False, help_text='新成员需要审批')),
                ('subject', models.CharField(blank=True, help_text='学习主题', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text='标签列表')),
                ('is_active', models.BooleanField(default=True, help_text='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='创建者', on_delete=django.db.models.deletion.CASCADE, related_name='created_study_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学习小组',
                'verbose_name_plural': '学习小组',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '群主'), ('admin', '管理员'), ('moderator', '版主'), ('member', '成员')], default='member', help_text='成员角色', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='是否活跃')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, help_text='邀请者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='成员用户', on_delete=django.db.models.deletion.CASCADE, related_name='study_group_memberships', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='所属小组', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.studygroup')),
            ],
            options={
                'verbose_name': '小组成员',
                'verbose_name_plural': '小组成员',
            },
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(help_text='邀请码', max_length=32, unique=True)),
                ('email', models.EmailField(blank=True, help_text='邀请邮箱', max_length=254)),
                ('message', models.TextField(blank=True, help_text='邀请消息')),
                ('status', models.CharField(choices=[('pending', '待接受'), ('accepted', '已接受'), ('declined', '已拒绝'), ('expired', '已过期')], default='pending', help_text='邀请状态', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, help_text='过期时间', null=True)),
                ('assigned_role', models.CharField(choices=[('owner', '群主'), ('admin', '管理员'), ('moderator', '版主'), ('member', '成员')], default='member', help_text='分配的角色', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(help_text='邀请者', on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations_created', to=settings.AUTH_USER_MODEL)),
                ('invitee', models.ForeignKey(blank=True, help_text='被邀请者', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations_received', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='目标小组', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='users.studygroup')),
            ],
            options={
                'verbose_name': '小组邀请',
                'verbose_name_plural': '小组邀请',
            },
        ),
        migrations.AddField(
            model_name='groupchannel',
            name='group',
            field=models.ForeignKey(help_text='所属学习小组', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='users.studygroup'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['privacy'], name='users_study_privacy_f5e739_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['created_by'], name='users_study_created_6efe05_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['subject'], name='users_study_subject_17590d_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['-created_at'], name='users_study_created_a7cd05_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['is_active'], name='users_study_is_acti_575e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group', 'role'], name='users_group_group_i_142dab_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['user', 'joined_at'], name='users_group_user_id_67fcf0_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['is_active'], name='users_group_is_acti_3653fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(fields=['invite_code'], name='users_group_invite__358126_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(fields=['status'], name='users_group_status_7dd1ef_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(fields=['expires_at'], name='users_group_expires_e2cb16_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(fields=['group', 'status'], name='users_group_group_i_268c56_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchannel',
            index=models.Index(fields=['group', 'order'], name='users_group_group_i_cf357b_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchannel',
            index=models.Index(fields=['group', 'channel_type'], name='users_group_group_i_12575c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchannel',
            index=models.Index(fields=['is_active'], name='users_group_is_acti_7661e9_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchannel',
            index=models.Index(fields=['-last_message_at'], name='users_group_last_me_d6a1be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupchannel',
            unique_together={('group', 'name')},
        ),
    ]
