# Generated by Django 6.0 on 2025-12-08 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(max_length=100)),
                ('difficulty_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('estimated_hours', models.FloatField(default=0)),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('learning_objectives', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_paths',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('estimated_minutes', models.IntegerField(default=60)),
                ('resources', models.JSONField(blank=True, default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path_steps', to='documents.document')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='study.learningpath')),
            ],
            options={
                'db_table': 'learning_path_steps',
                'ordering': ['learning_path', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudyGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_type', models.CharField(choices=[('pages', '页数'), ('time', '时间'), ('concepts', '概念数'), ('documents', '文档数'), ('sessions', '会话数')], max_length=20)),
                ('target_value', models.IntegerField()),
                ('current_value', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyHabit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('habit_type', models.CharField(choices=[('daily_time', '每日学习时间'), ('daily_pages', '每日阅读页数'), ('review_frequency', '复习频率'), ('note_taking', '笔记习惯'), ('flashcard_usage', '卡片使用')], max_length=20)),
                ('target_value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_habits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('pages_read', models.IntegerField(default=0)),
                ('concepts_learned', models.IntegerField(default=0)),
                ('notes_created', models.IntegerField(default=0)),
                ('flashcards_reviewed', models.IntegerField(default=0)),
                ('session_type', models.CharField(choices=[('reading', '阅读'), ('review', '复习'), ('practice', '练习'), ('other', '其他')], default='reading', max_length=20)),
                ('focus_score', models.FloatField(blank=True, null=True)),
                ('comprehension_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudyStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_study_time', models.IntegerField(default=0)),
                ('documents_read', models.IntegerField(default=0)),
                ('pages_read', models.IntegerField(default=0)),
                ('concepts_learned', models.IntegerField(default=0)),
                ('notes_created', models.IntegerField(default=0)),
                ('flashcards_reviewed', models.IntegerField(default=0)),
                ('flashcards_correct', models.IntegerField(default=0)),
                ('study_sessions', models.IntegerField(default=0)),
                ('average_focus_score', models.FloatField(blank=True, null=True)),
                ('average_comprehension_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['user', 'is_active'], name='learning_pa_user_id_57f898_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['domain'], name='learning_pa_domain_3d575e_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpathstep',
            index=models.Index(fields=['learning_path', 'order'], name='learning_pa_learnin_e29193_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpathstep',
            index=models.Index(fields=['is_completed'], name='learning_pa_is_comp_19034c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learningpathstep',
            unique_together={('learning_path', 'order')},
        ),
        migrations.AddIndex(
            model_name='studygoal',
            index=models.Index(fields=['user', 'is_completed'], name='study_goals_user_id_f4f3a9_idx'),
        ),
        migrations.AddIndex(
            model_name='studygoal',
            index=models.Index(fields=['end_date'], name='study_goals_end_dat_2c8232_idx'),
        ),
        migrations.AddIndex(
            model_name='studyhabit',
            index=models.Index(fields=['user', 'habit_type'], name='study_habit_user_id_82f91e_idx'),
        ),
        migrations.AddIndex(
            model_name='studyhabit',
            index=models.Index(fields=['is_active'], name='study_habit_is_acti_289504_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studyhabit',
            unique_together={('user', 'habit_type')},
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', '-start_time'], name='study_sessi_user_id_260040_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['document'], name='study_sessi_documen_63f881_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['session_type'], name='study_sessi_session_405498_idx'),
        ),
        migrations.AddIndex(
            model_name='studystatistic',
            index=models.Index(fields=['user', '-date'], name='study_stati_user_id_943145_idx'),
        ),
        migrations.AddIndex(
            model_name='studystatistic',
            index=models.Index(fields=['date'], name='study_stati_date_bd1157_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studystatistic',
            unique_together={('user', 'date')},
        ),
    ]
