# Generated by Django 6.0 on 2025-12-10 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_collections_count_document_likes_count_and_more'),
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=200)),
                ('pronunciation', models.CharField(blank=True, max_length=500)),
                ('definition', models.TextField(blank=True)),
                ('translation', models.TextField(blank=True)),
                ('example_sentence', models.TextField(blank=True)),
                ('example_translation', models.TextField(blank=True)),
                ('context', models.TextField(blank=True)),
                ('mastery_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=1)),
                ('review_count', models.IntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('general', '通用'), ('academic', '学术'), ('technical', '技术'), ('business', '商务'), ('daily', '日常'), ('custom', '自定义')], default='general', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabulary_words', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vocabulary',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('word_count', models.IntegerField(default=0)),
                ('mastered_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vocabulary_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyListMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_memberships', to='study.vocabulary')),
                ('vocabulary_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_memberships', to='study.vocabularylist')),
            ],
            options={
                'db_table': 'vocabulary_list_memberships',
            },
        ),
        migrations.CreateModel(
            name='VocabularyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField()),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('difficulty_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('review_type', models.CharField(choices=[('flashcard', '闪卡'), ('spelling', '拼写'), ('multiple_choice', '选择题'), ('meaning', '释义')], default='flashcard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_reviews', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='study.vocabulary')),
            ],
            options={
                'db_table': 'vocabulary_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['user', '-created_at'], name='vocabulary_user_id_adf775_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['user', 'word'], name='vocabulary_user_id_100465_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['user', 'category'], name='vocabulary_user_id_a3ab7a_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['user', 'mastery_level'], name='vocabulary_user_id_10fa85_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['user', 'is_favorite'], name='vocabulary_user_id_4e8d8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vocabulary',
            unique_together={('user', 'word')},
        ),
        migrations.AddIndex(
            model_name='vocabularylist',
            index=models.Index(fields=['user', '-created_at'], name='vocabulary__user_id_aa2ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularylist',
            index=models.Index(fields=['user', 'is_default'], name='vocabulary__user_id_42704c_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularylist',
            index=models.Index(fields=['is_public'], name='vocabulary__is_publ_eb4eae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vocabularylist',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='vocabularylistmembership',
            unique_together={('vocabulary', 'vocabulary_list')},
        ),
        migrations.AddIndex(
            model_name='vocabularyreview',
            index=models.Index(fields=['vocabulary', '-created_at'], name='vocabulary__vocabul_a7c58c_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyreview',
            index=models.Index(fields=['user', '-created_at'], name='vocabulary__user_id_e234a9_idx'),
        ),
    ]
