# Generated by Django 5.2.9 on 2025-12-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_vocabulary_vocabularylist_vocabularylistmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='primary_language',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='secondary_language',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese')], default='zh', max_length=10),
        ),
    ]
