# Generated by Django 6.0 on 2025-12-09 06:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='日期')),
                ('daily_input_tokens', models.PositiveBigIntegerField(default=0, verbose_name='当日输入token数')),
                ('daily_output_tokens', models.PositiveBigIntegerField(default=0, verbose_name='当日输出token数')),
                ('daily_total_tokens', models.PositiveBigIntegerField(default=0, verbose_name='当日总token数')),
                ('daily_api_calls', models.PositiveIntegerField(default=0, verbose_name='当日API调用次数')),
                ('total_input_tokens', models.PositiveBigIntegerField(default=0, verbose_name='累计输入token数')),
                ('total_output_tokens', models.PositiveBigIntegerField(default=0, verbose_name='累计输出token数')),
                ('total_tokens', models.PositiveBigIntegerField(default=0, verbose_name='累计总token数')),
                ('total_api_calls', models.PositiveIntegerField(default=0, verbose_name='累计API调用次数')),
            ],
            options={
                'verbose_name': '系统token使用统计',
                'verbose_name_plural': '系统token使用统计',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserTokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_input_tokens', models.PositiveBigIntegerField(default=0, verbose_name='总输入token数')),
                ('total_output_tokens', models.PositiveBigIntegerField(default=0, verbose_name='总输出token数')),
                ('total_tokens', models.PositiveBigIntegerField(default=0, verbose_name='总token数')),
                ('api_call_count', models.PositiveIntegerField(default=0, verbose_name='API调用次数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户token使用统计',
                'verbose_name_plural': '用户token使用统计',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='TokenUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('ai_chat', 'AI聊天'), ('agent_execution', 'Agent执行'), ('document_index', '文档索引'), ('other', '其他')], default='other', max_length=20, verbose_name='API类型')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='输入token数')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='输出token数')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='总token数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='调用时间')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='元数据')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'token使用记录',
                'verbose_name_plural': 'token使用记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='billing_tok_user_id_6a6c94_idx'), models.Index(fields=['api_type', '-created_at'], name='billing_tok_api_typ_8fd545_idx')],
            },
        ),
    ]
