# Generated by Django 6.0 on 2025-12-08 05:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('concept_type', models.CharField(choices=[('definition', '定义'), ('theorem', '定理'), ('lemma', '引理'), ('method', '方法'), ('formula', '公式'), ('other', '其他')], max_length=20)),
                ('description', models.TextField()),
                ('formula', models.TextField(blank=True)),
                ('location_section', models.CharField(blank=True, max_length=500)),
                ('location_line', models.IntegerField(blank=True, null=True)),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('related_concepts', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=1.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='documents.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_concepts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConceptRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('prerequisite', '前置关系'), ('related', '相关关系'), ('extends', '扩展关系'), ('example_of', '示例关系'), ('part_of', '部分关系'), ('contrast', '对比关系')], max_length=20)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(default='system', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='knowledge.concept')),
                ('target_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='knowledge.concept')),
            ],
            options={
                'db_table': 'concept_relations',
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('difficulty', models.IntegerField(default=0)),
                ('next_review_date', models.DateField()),
                ('review_count', models.IntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval', models.IntegerField(default=1)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_flashcards',
                'ordering': ['next_review_date'],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('color', models.CharField(default='yellow', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('start_line', models.IntegerField()),
                ('end_line', models.IntegerField()),
                ('start_char', models.IntegerField(default=0)),
                ('end_char', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlights', to='documents.documentchunk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_highlights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='documents.documentchunk')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='documents.document')),
                ('linked_concepts', models.ManyToManyField(blank=True, related_name='notes', to='knowledge.concept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_notes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['user', 'name'], name='knowledge_c_user_id_109142_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['document', 'concept_type'], name='knowledge_c_documen_97cbff_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['concept_type'], name='knowledge_c_concept_dc6984_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['name'], name='knowledge_c_name_63a935_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='concept',
            unique_together={('user', 'document', 'name', 'location_line')},
        ),
        migrations.AddIndex(
            model_name='conceptrelation',
            index=models.Index(fields=['source_concept', 'relation_type'], name='concept_rel_source__bb745d_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptrelation',
            index=models.Index(fields=['target_concept', 'relation_type'], name='concept_rel_target__90fe48_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptrelation',
            index=models.Index(fields=['relation_type'], name='concept_rel_relatio_eb9719_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conceptrelation',
            unique_together={('source_concept', 'target_concept', 'relation_type')},
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'next_review_date'], name='knowledge_f_user_id_c0815c_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'is_active'], name='knowledge_f_user_id_51d905_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['difficulty'], name='knowledge_f_difficu_49b6ab_idx'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['user', 'document'], name='knowledge_h_user_id_e7ceba_idx'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['document'], name='knowledge_h_documen_b08e58_idx'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['chunk'], name='knowledge_h_chunk_i_c64e19_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-updated_at'], name='knowledge_n_user_id_f5cb53_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['document'], name='knowledge_n_documen_8e20ba_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_public'], name='knowledge_n_is_publ_0f0e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_bookmarked'], name='knowledge_n_is_book_eaa0ca_idx'),
        ),
    ]
