# Generated by Django 6.0 on 2025-12-08 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_documents_d_user_id_ffacf2_idx_and_more'),
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='flashcard',
            name='knowledge_f_user_id_51d905_idx',
        ),
        migrations.AddField(
            model_name='concept',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='concept',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concepts', to='documents.documentchunk'),
        ),
        migrations.AddField(
            model_name='concept',
            name='definition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='difficulty',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='concept',
            name='examples',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='concept',
            name='importance',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='concept',
            name='is_mastered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concept',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='concept',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='mastery_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concept',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='documents.documentchunk'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='deck',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='documents.document'),
        ),
        migrations.AddField(
            model_name='note',
            name='folder',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='note',
            name='importance',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='note',
            name='is_mastered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('summary', '总结'), ('question', '问题'), ('insight', '见解'), ('method', '方法'), ('example', '示例'), ('other', '其他')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['user', 'concept_type'], name='knowledge_c_user_id_0b4c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['user', 'is_mastered'], name='knowledge_c_user_id_07bc5d_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['user', '-importance', 'name'], name='knowledge_c_user_id_c1a2af_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['chunk'], name='knowledge_c_chunk_i_6706c2_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'deck'], name='knowledge_f_user_id_3ef89c_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'is_active', 'next_review_date'], name='knowledge_f_user_id_565146_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['document'], name='knowledge_f_documen_88a110_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['chunk'], name='knowledge_f_chunk_i_f63687_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'note_type'], name='knowledge_n_user_id_d3cf4b_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'folder'], name='knowledge_n_user_id_71140a_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['chunk'], name='knowledge_n_chunk_i_006cfb_idx'),
        ),
    ]
