# Generated by Django 6.0 on 2025-12-08 06:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_documents_d_user_id_ffacf2_idx_and_more'),
        ('knowledge', '0002_remove_flashcard_knowledge_f_user_id_51d905_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(0, '完全忘记'), (1, '不太记得'), (2, '有点印象'), (3, '基本记得'), (4, '记得清楚'), (5, '完全记得')])),
                ('review_time', models.IntegerField()),
                ('previous_interval', models.IntegerField()),
                ('previous_ease_factor', models.FloatField()),
                ('new_interval', models.IntegerField()),
                ('new_ease_factor', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'flashcard_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('cards_studied', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('incorrect_answers', models.IntegerField(default=0)),
                ('session_type', models.CharField(default='review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'knowledge_study_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='highlight',
            name='highlight_type',
            field=models.CharField(choices=[('important', '重要'), ('question', '疑问'), ('insight', '见解'), ('example', '示例'), ('other', '其他')], default='important', max_length=20),
        ),
        migrations.AddField(
            model_name='highlight',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='highlight',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='quoted_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='highlight',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['user', 'highlight_type'], name='knowledge_h_user_id_0b20bc_idx'),
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='flashcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='knowledge.flashcard'),
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_study_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='flashcardreview',
            index=models.Index(fields=['user', 'flashcard'], name='flashcard_r_user_id_61a43e_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardreview',
            index=models.Index(fields=['flashcard'], name='flashcard_r_flashca_4e1c94_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardreview',
            index=models.Index(fields=['rating'], name='flashcard_r_rating_b8bf3a_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', '-start_time'], name='knowledge_s_user_id_66cb6d_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['session_type'], name='knowledge_s_session_c8e417_idx'),
        ),
    ]
