# Generated by Django 6.0 on 2025-12-10 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_flashcardreview_studysession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('change_type', models.CharField(choices=[('created', '创建'), ('updated', '更新'), ('restored', '恢复')], max_length=20)),
                ('change_summary', models.TextField(blank=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='knowledge.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_note_history',
                'ordering': ['-edited_at'],
                'indexes': [models.Index(fields=['note', '-edited_at'], name='knowledge_n_note_id_3afc02_idx'), models.Index(fields=['user', '-edited_at'], name='knowledge_n_user_id_2b59ba_idx'), models.Index(fields=['change_type'], name='knowledge_n_change__2bf1c5_idx')],
            },
        ),
    ]
