# Generated by Django 5.0 on 2025-12-08 01:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('md', 'Markdown'), ('tex', 'LaTeX')], max_length=10)),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('processing', '处理中'), ('ready', '就绪'), ('error', '错误')], default='uploading', max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('raw_content', models.TextField(blank=True)),
                ('cleaned_content', models.TextField(blank=True)),
                ('index_data', models.JSONField(default=dict)),
                ('word_count', models.IntegerField(default=0)),
                ('chunk_count', models.IntegerField(default=0)),
                ('formula_count', models.IntegerField(default=0)),
                ('reading_progress', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('chunk_type', models.CharField(choices=[('section', '章节'), ('paragraph', '段落'), ('theorem', '定理'), ('definition', '定义'), ('example', '示例'), ('proof', '证明'), ('figure', '图表'), ('table', '表格'), ('other', '其他')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('start_line', models.IntegerField(default=0)),
                ('end_line', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'ordering': ['document', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('start_line', models.IntegerField(default=0)),
                ('end_line', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='documents.document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentsection')),
            ],
            options={
                'ordering': ['document', 'level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latex', models.TextField()),
                ('formula_type', models.CharField(choices=[('inline', '行内公式'), ('display', '独立公式'), ('equation', '带编号公式')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('variables', models.JSONField(default=list)),
                ('context', models.TextField(blank=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='documents.document')),
            ],
            options={
                'ordering': ['document', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'created_at'], name='documents_d_user_id_ffacf2_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'order'], name='documents_d_documen_8bac24_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['chunk_type'], name='documents_d_chunk_t_9e5d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsection',
            index=models.Index(fields=['document', 'parent'], name='documents_d_documen_fb5978_idx'),
        ),
        migrations.AddIndex(
            model_name='formula',
            index=models.Index(fields=['document'], name='documents_f_documen_bd380b_idx'),
        ),
    ]
