# Generated by Django 6.0 on 2025-12-08 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_user_id_ffacf2_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_status_07369e_idx',
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'status'], name='documents_d_user_id_200c84_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', '-created_at'], name='documents_d_user_id_a8f8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'file_type'], name='documents_d_user_id_7b2a85_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'created_at'], name='documents_d_status_64808e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_type'], name='documents_d_documen_776968_idx'),
        ),
    ]
