# Generated by Django 6.0 on 2025-12-08 23:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_file_size_document_original_filename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, help_text='文档描述'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='是否收藏'),
        ),
        migrations.AddField(
            model_name='document',
            name='privacy',
            field=models.CharField(choices=[('private', '私有'), ('public', '公开'), ('favorite', '收藏'), ('all', '全部')], default='private', help_text='文档隐私设置', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='文档标签'),
        ),
        migrations.AddField(
            model_name='document',
            name='view_count',
            field=models.IntegerField(default=0, help_text='查看次数'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'privacy'], name='documents_d_user_id_398c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'is_favorite'], name='documents_d_user_id_d059ba_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['privacy', 'status'], name='documents_d_privacy_a03941_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_favorite', '-created_at'], name='documents_d_is_favo_5e6751_idx'),
        ),
    ]
