# Generated by Django 6.0 on 2025-12-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_description_document_is_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='error_message',
            field=models.TextField(blank=True, help_text='错误信息（如果处理失败）'),
        ),
    ]
