# Generated by Django 6.0 on 2025-12-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='label',
            field=models.CharField(blank=True, help_text='公式标签（如 eq:1）', max_length=200),
        ),
        migrations.AddField(
            model_name='formula',
            name='order',
            field=models.IntegerField(default=0, help_text='公式在文档中的顺序'),
        ),
    ]
