# Generated by Django 6.0 on 2025-12-09 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_formula_label_formula_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='collections_count',
            field=models.PositiveIntegerField(default=0, help_text='收藏数'),
        ),
        migrations.AddField(
            model_name='document',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, help_text='点赞数'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-likes_count'], name='documents_d_likes_c_dc9ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-collections_count'], name='documents_d_collect_08d845_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-view_count'], name='documents_d_view_co_6654d6_idx'),
        ),
    ]
