# Generated by Django 6.0 on 2025-12-10 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_collections_count_document_likes_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_read_at', models.DateTimeField(auto_now_add=True, help_text='首次阅读时间')),
                ('last_read_at', models.DateTimeField(auto_now=True, help_text='最后阅读时间')),
                ('scroll_position', models.FloatField(default=0.0, help_text='滚动位置（0-1）')),
                ('read_count', models.PositiveIntegerField(default=1, help_text='阅读次数')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_read_at'],
                'indexes': [models.Index(fields=['user', '-last_read_at'], name='documents_r_user_id_774b0d_idx'), models.Index(fields=['user', 'document'], name='documents_r_user_id_ae7d11_idx'), models.Index(fields=['document', '-last_read_at'], name='documents_r_documen_c46f08_idx')],
                'unique_together': {('user', 'document')},
            },
        ),
    ]
